version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    # Update the npm manifest file to relax
    # the version requirements as js-waku is a library
    versioning-strategy: widen
    # Do not auto rebase, let bors handle this
    rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/examples/web-chat"
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-patch", "version-update:semver-minor"]
    # Do not auto rebase, let bors handle this
    rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/examples/relay-reactjs-chat"
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-patch", "version-update:semver-minor"]
    # Do not auto rebase, let bors handle this
    rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/examples/store-reactjs-chat"
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-patch", "version-update:semver-minor"]
    # Do not auto rebase, let bors handle this
    rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/examples/eth-pm"
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-patch", "version-update:semver-minor"]
    # Do not auto rebase, let bors handle this
    rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/examples/eth-pm-wallet-encryption"
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-patch", "version-update:semver-minor"]
    # Do not auto rebase, let bors handle this
    rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/examples/relay-angular-chat"
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    ignore:
      - dependency-name: "*"
        update-types:
          ["version-update:semver-patch", "version-update:semver-minor"]
    # Do not auto rebase, let bors handle this
    rebase-strategy: "disabled"
