name: Webchat Deploy GH Pages

on:
  push:
    branches:
      - 'main'

jobs:
  deploy_gh_pages:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set git author identity
        run: |
          git config user.name "GitHub Action On waku-js Repo"
          git config user.email "franck+ghpages@status.im"

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-v1-${{ hashFiles('**/package-lock.json') }}

      - name: "[waku-js] install using npm ci"
        uses: bahmutov/npm-install@v1

      - name: "[waku-js] build"
        run: npm run build

      - name: install using npm i
        run: npm install
        working-directory: examples/web-chat

      - name: build web app
        run: npm run build
        working-directory: examples/web-chat

      - name: Deploy web chat app on gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/web-chat/build

      - name: Generate docs
        run: npm run doc:html

      - name: Deploy documentation on gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true # Do not delete web chat app
          publish_dir: ./build/docs
          destination_dir: docs
